### ISSUE TITLE
Metadata is uploaded incorrectly

### ISSUE THREAD

**Issue by ldmberman** [0xEnrico/arweave-nft-uploader#14]
There is a [bug](https://github.com/MikeHibbert/arweave-python-client/issues/26) in `arweave-python-client` where data passed directly to a `Transaction` object is not uploaded correctly. It computes `data_root` from the [Base64URL encoded](https://github.com/MikeHibbert/arweave-python-client/blob/master/arweave/arweave_lib.py#L115) data so the nodes do not recognize it and do not accept the original data.

[An example](https://arweave.net/tx/7AZJq7Dqjo1LHBfU69PIAmTSkK8iBM5mXP-0JJf9Izo). `data_root` computed from the raw data is `yiIbdak6AXJ17hGF5EJC_FpleCvd3pBe2c4jSZpRDVM` whereas the tx was signed with `XTcZfQOhQ0byq0NjAfJbYynVMyX6fkd4IBIfRR3S0IA` - the value consistent with computing `data_root` from a Base64URL encoded blob.

One quick workaround I have in mind is to always pass data to `Transaction` via a file handler (then it goes through a different code path which does not appear to have this bug), i.e., [here](https://github.com/0xEnrico/arweave-nft-uploader/blob/main/arweave_nft_uploader/__init__.py#L168) do:

```
fp = tempfile.NamedTemporaryFile()
fp.write(json.dumps(asset_data))
fp.seek(0)
tx = Transaction(wallet, file_handler=fp, file_path=fp.name)
```

**Comment by 0xEnrico** [comment]
Can you please provide a pull request for this?

I've moved to other Solana projects now, I have difficulties implementing
and testing a fix.


Il lun 3 gen 2022, 13:15 Lev Berman ***@***.***> ha scritto:

**Comment by ldmberman** [comment]
Hi @0xEnrico, thank you for the quick reply. I've opened https://github.com/0xEnrico/arweave-nft-uploader/pull/15. I have successfully uploaded a metadata file using that code.

**Comment by 0xEnrico** [comment]
But, out of curiosity... How could my uploader even work with that bug? :open_mouth:

**Comment by ldmberman** [comment]
> I removed the duplicated fp.seek(0) because it should be necessary just once

The data is read twice - the first time in `sign()` where it needs to compute the data root, the second time - in `get_uploader` thus the second seek.

> How could my uploader even work with that bug?

The data is cached by `arweave.net` (it simply caches the data field) while nodes check the merkle proofs before storing data. If proofs are not uploaded but data is provided in the "data" field, the nodes expect a particular merkle tree and do not store data if the expected way of splitting it does not yield the signed data_root.

**Comment by ldmberman** [comment]
> the second time - in get_uploader thus the second seek.

Ah, no, it works in fact, nevermind. Thank you for the quick merging!
