### ISSUE TITLE
ERROR local variable 'ex' referenced before assignment

### ISSUE THREAD

**Issue by eXiiov** [0xEnrico/arweave-nft-uploader#4]
I get this error during the second step

**Comment by eXiiov** [comment]
fixed commandline error

**Comment by eXiiov** [comment]
Still same issue occuring.

**Comment by 0xEnrico** [comment]
I made a fix (please update with pip install -U git+https://github.com/0xEnrico/arweave-nft-uploader.git) BUT if you get that error, you have an error in your .json files.

**Comment by eXiiov** [comment]
I tried and am still having the error. I think it is because im trying to use gifs only. png upload worked for me flawlessly. I am guessing --assets-from-json is expecting two uri's instead of one. Is there a quick fix I can make for it to accept .gif instead of .png as default?

Thanks Enrico

**Comment by eXiiov** [comment]
I have fixed it by modifying the file to work with gifs. 

Thanks Enrico
