### ISSUE TITLE
Candy machine skipping tokens for low mint price

### ISSUE THREAD

**Issue by shibaji** [0xEnrico/arweave-nft-uploader#7]
Hi Enrico,

Thanks for providing the tool, and everything went ok, but it seems the candy machine skips some token when low mint price is specified - just wanted to ensure that it has nothing to do with using this tool, as it is just setting up the storage? I filed this bug also at metaplex, but no response so far: https://github.com/metaplex-foundation/metaplex/issues/936

Please help sir.

Thanks

**Comment by 0xEnrico** [comment]
Hi Shibaji, I confirm that my tool is just for the storage, it has nothing to do with the mint.
