### ISSUE TITLE
Solana expenses question

### ISSUE THREAD

**Issue by eroliko** [0xEnrico/arweave-nft-uploader#9]
Hi Enrico,

I’ve successfully managed to upload my assets using your tool, but I am confused about Sol expenses. When I upload 10000 images using `metaplex upload` command it costs me around 17 SOLs. I hope(d) that this tool can make it much cheaper, because I would pay for uploading 1 image by SOL, then the rest by AR, and that’s it. Sadly, however after I rebuild Candy Machine, it’s again 17 SOLs. Is it possible that I did something wrong or there is just no way how to avoid paying all those fees on Solana? I was very careful about being in the same folder all the time, actually it had to be `metaplex/js/packages/cli`, otherwise it wouldn’t work.

**Comment by 0xEnrico** [comment]
Hello, there is a fixed cost for creating the CM. That cost is not avoided
using my uploader. Please check https://www.feecalc.live/


Il giorno mer 1 dic 2021 alle ore 15:02 eroliko ***@***.***>
ha scritto:
